### ISSUE TITLE
crash (Im not a java expert)

### ISSUE THREAD

**Issue by RhysHolloway** [TeamBR-Modding/Bookshelf#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  AllTheItems (AllTheItems-mc1.8-1.1.jar)
  FairyLightsLoadingPlugin (fairylights-1.2-1.8.jar)
  Init (RepairUnlimited1.8.jar)
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  WallpaperLoadingPlugin (wallpaper-0.4-1.8.jar)
  BowInfinityFix (BowInfinityFix-1.8-rv1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.8-1.5.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  Transformer (EasyZoom[1.8][Forge].jar)
  LoadingPlugin (VersionChecker-1.2.2.jar)
  LoadingPlugin (Bloodmoon-1.2.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  LoadingPlugin (FastLeaveDecay-1.0.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1373-universal.jar)
  Core (NoSlimeInFlatland_v1.0.0[1.8].jar)
  EWFMLPlugin ([1.8]ExtendedWorkbench v1.3 beta.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  nceCore (NoCreeperExplosions_v1.0.1[1.8].jar)
  Plugin (VillagerInv_v1.0.2[1.8][FML].jar)
  ZSFMLLoadingPlugin (ZombieSunscreenCore.jar)
  HxCLoader (HxCCore-1.8-1.5.1-universal.jar)
  Java8CheckerCoremod (Java8Checker  MC-1.8+  v1.1.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.5.jar)
  MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 9/18/15 5:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/network/IGuiHandler
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/network/IGuiHandler
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.network.IGuiHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 34 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 127873144 bytes (121 MB) / 321216512 bytes (306 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1514 155 mods loaded, 154 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1514.jar) 
    UC  Forge{11.14.3.1514} [Minecraft Forge](forge-1.8-11.14.3.1514.jar) 
    UC  AllTheItems{1.1} [AllTheItems](minecraft.jar) 
    UC  Aroma1997Core{1.0.3.4} [Aroma1997Core](Aroma1997Core-1.8-1.0.3.4.jar) 
    UC  bowinfinityfix{rv1} [Bow Infinity Fix](minecraft.jar) 
    UC  CodeChickenCore{1.0.5.36} [CodeChicken Core](minecraft.jar) 
    UC  EAZY-ZOOM{0.0.0} [EAZY ZOOM for Forge](minecraft.jar) 
    UC  NCE-CORE{1.0.1} [No Creeper Explorsions!](minecraft.jar) 
    UC  NSF-CORE{1.0.0} [No Slime in Flatland](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UC  REPAIR_UNLIMITED{0.0.0} [Repair Unlimited](minecraft.jar) 
    UC  VILLAGERINV{1.0.2} [Villagers Inventory Viewer for FML](minecraft.jar) 
    UC  darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE](minecraft.jar) 
    UC  HxCCore-ASM{1.5.1} [HxCKDMS Core ASM](minecraft.jar) 
    UC  dynamicswordskills{1.8-2.0} [Dynamic Sword Skills](1.8-dynamicswordskills-2.0.jar) 
    UC  arrowcam{1.1} [Arrow Camera](1.8_arrowcam_v1.2.jar) 
    UC  ChickenShed{1.1.4} [Chicken Shed]([1.8] ChickenShed %28v1.2.0%29 %281%29.jar) 
    UC  extendedWorkbench{1.3} [Extended Workbench]([1.8]ExtendedWorkbench v1.3 beta.jar) 
    UC  advInv{0.5.11} [Advanced Inventory](advInv-0.5.11-MC1.8.jar) 
    UC  AfraidOfTheDark{1.8-1.0} [Afraid of the Dark](AfraidOfTheDark-1.8-1.0.jar) 
    UC  satscapealarmcraft{1.0} [Alarmcraft](Alarmcraft-1.0-%281.8%29.jar) 
    UC  uap{1.1.0} [Animal Research Machine](AnimalResearchMachine-15.6.26-1.0.0-1.8.jar) 
    UC  MovingWorld{MC1.8-V1.8.1} [Moving World](movingworld-MC1.8-V1.8.1.jar) 
    UC  ArchimedesShipsPlus{MC1.8-V1.8} [Archimedes' Ships Plus](archimedesshipsplus-MC1.8-V1.8.jar) 
    UC  ArmorEffect{1.8} [Armor Effect Mod](ArmorEffectMod-1.2.0.jar) 
    UC  Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper](Aroma1997Core-1.8-1.0.3.4.jar) 
    UC  Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.8-1.1.1.0.jar) 
    UC  AromaBackup{0.0.1.0} [AromaBackup](AromaBackup-1.8-0.0.1.0.jar) 
    UC  AutoSapling{1.0} [AutoSapling](AutoSap-MC1.8-1.2.jar) 
    UC  iChunUtil{5.4.0} [iChunUtil](iChunUtil-5.4.0.jar) 
    UC  BackTools{5.1.0} [BackTools](BackTools-5.1.0.jar) 
    UC  bm{1.1} [The Bagel Mod](BagelMod-v1.1-%28mc1.8%29.jar) 
    UC  Baubles{1.1.1.0} [Baubles](Baubles-1.8-1.1.1.0.jar) 
    UC  BBG{2.0.0} [BetterBedrockGen](BBG 1.8-2.0.0.jar) 
    UC  bedrockbreaker{1.0.4.1} [Bedrock Breaker](Bedrock Breaker-1.0.4.1.jar) 
    UC  BetterFoliage{1.1.5} [Better Foliage](BetterFoliage-mc1.8-1.1.5.jar) 
    UC  Betterrecipes{1.1.2} [Betterrecipes](Betterrecipes 1.1.2.jar) 
    UC  BetterSprinting{1.1.1} [Better Sprinting](BetterSprinting  MC-1.8  v1.1.1.jar) 
    UC  BetterTitleScreen{1.8-1.1a} [Better Title Screen](BetterTitleScreen-1.8-1.1a.jar) 
    UC  bettervillages{0.5} [Better Villages Mod](BetterVillages-0.5%281.8%29.jar) 
    UC  BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8-3.0.0.1373-universal.jar) 
    UC  buffalo{1.0} [Bison Mod](bisonmod.jar) 
    UC  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8-1.4.0-1.jar) 
    UC  Bloodmoon{1.2} [Bloodmoon](Bloodmoon-1.2.jar) 
    UE  bookshelf{2.0.3} [Bookshelf](Bookshelf-1.8-2.0.3.jar) 
    UC  C4Lib{1.0.0} [C4Lib](C4Lib-1.8-1.0.0-universal.jar) 
    UC  fusionutil{0.1} [FusionUtil](FusionUtil-0.1.6.jar) 
    UC  cabinets3{version} [Cabinets Reloaded](Cabinets Reloaded-3.0.45.jar) 
    UC  samscarbonpaper{1.8-1.0.0} [Carbon Paper](CarbonPaper-1.8-1.0.0.jar) 
    UC  Chameleon{1.8-0.1.0} [Chameleon](Chameleon-1.8-0.1.0.jar) 
    UC  CharacterOnGui{1.0} [CharacterOnGui](CharacterOnGui-1.8-1.3.jar) 
    UC  clayworldgen{v1.0.0} [ClayWorldGen](Clay WorldGen v1.0.0 1.8.jar) 
    UC  MINE_CONTAINER{1.0} [Container capture](ContainerCapture1.8_r2.jar) 
    UC  customnpcs{1.8.0_beta} [CustomNpcs](CustomNPCs_1.8.0_beta.jar) 
    UC  TeNNoX_CustomSelectionBox{1.4} [CustomSelectionBox](CustomSelectionBox-1.8-1.4.jar) 
    UC  lootablebodies{1.3.5} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.3.5.jar) 
    UC  cyclopscore{0.1.1} [Cyclops Core](CyclopsCore-1.8-0.1.1.jar) 
    UC  DeathCounter{5.0.0} [DeathCounter](DeathCounter-5.0.0.jar) 
    UC  Ding{MC1.8.0} [Ding](Ding-MC1.8.0.jar) 
    UC  DungeonPack{1.8} [DungeonPack](dungeonpack-1.8.jar) 
    UC  EAZY-ZOOM_{0.0.0} [EAZY-ZOOM_INGAME_KEYBINDER](EasyZoom[1.8][Forge].jar) 
    UC  eplus{3.1.0a1} [Enchanting Plus](EnchantingPlus-1.8-3.1.0a1.jar) 
    UC  enderutilities{0.4.0-beta-1a} [Ender Utilities](enderutilities-1.8-0.4.0-beta-1a.jar) 
    UC  EnderZoo{1.8-1.1.24_beta} [Ender Zoo](EnderZoo-1.8-1.1.24_beta.jar) 
    UC  enhancedspawnerstwo{0.2} [enhancedspawnerstwo](Enhanced Spawners 2 - 2.0.jar) 
    UC  evilcraft{0.8.2} [EvilCraft](EvilCraft-1.8-0.8.2.jar) 
    UC  exnihilo2{0.27} [Ex Nihilo 2](ExNihilo2-0.27.jar) 
    UC  expandedrailsmod{1.7} [Expanded Rails Mod](ExpandedRailsModv1.7--1.8.jar) 
    UC  expchest{4.0} [Exp Chest](expchest-4.0.jar) 
    UC  et{1.0.0} [Exp-Translation](ExpTranslation-1.0.0-1.8.7.jar) 
    UC  extraachievements{2.3.0} [Extra Achievements](Extra Achievements 2.3.0.jar) 
    UC  extrafood{v1.1} [Extra Food Mod](ExtraFood-1.1.jar) 
    UC  fairylights{1.2} [Fairy Lights](fairylights-1.2-1.8.jar) 
    UC  FastLeaveDecay{1.0} [Fast Leave Decay](FastLeaveDecay-1.0.jar) 
    UC  fluxducts{1.0.2} [Flux Ducts](fluxducts-mc1.8-1.0.2.jar) 
    UC  glass_shards{1.3.2} [Glass Shards](glass_shards_mc1.8-1.3.2.jar) 
    UC  GravityGun{5.0.0} [GravityGun](GravityGun-5.0.0.jar) 
    UC  guideapi{1.8-1.0.0-21} [Guide-API](Guide-API-1.8-1.0.0-21.jar) 
    UC  GuiltTrip{5.0.0} [GuiltTrip](GuiltTrip-5.0.0.jar) 
    UC  HardcoreDarkness{1.5} [Hardcore Darkness](HardcoreDarkness-MC1.8-1.5.jar) 
    UC  wuppy29_harderpeaceful{1.8.0} [Harder Peaceful](Harder Peaceful 1.8.0-1.8.0.jar) 
    UC  HelpFixer{1.1.9} [HelpFixer](HelpFixer-1.1.9.jar) 
    UC  hopperducts{1.4.5} [Hopper Ducts](hopperducts-mc1.8-1.4.5.jar) 
    UC  hungryanimals{1.8-11.14.3.1499-2.1} [Hungry Animals](hungryanimals-2.1.alpha01.jar) 
    UC  HxCCore{1.5.1} [HxCKDMS-Core](HxCCore-1.8-1.5.1-universal.jar) 
    UC  HxCEnchants{1.8-1.6.4} [HxC Enchants](HxCEnchants-1.8-1.6.4.jar) 
    UC  igneousadditions{1.2-BETA-2} [Igneous Additions](IgneousAdditions-1.2-BETA-2.jar) 
    UC  IGWMod{1.2.0-27} [In-Game wiki Mod](IGW-Mod-1.8-1.2.0-27-universal.jar) 
    UC  wuppy29_improvedmobspawn{1.6.0} [Improved Mob Spawn](Improved Mob Spawn 1.8.0-1.6.0.jar) 
    UC  imc{1.8.0} [Improving Minecraft](Improving Minecraft-1.8.0.jar) 
    UC  VersionChecker{1.2.2} [Version Checker](VersionChecker-1.2.2.jar) 
    UC  IngameAccountSwitcher{2.2.2.0} [In-Game Account Switcher](In-Game Account Switcher 2.2.2.0.jar) 
    UC  IngameAccountSwitchervc{1.0} [In-game Account Switcher Version Checker](In-Game Account Switcher 2.2.2.0.jar) 
    UC  samsinvcrafting{1.8-1.0.1} [Inventory Crafitng Table](InventoryCrafting-1.8-1.0.1.jar) 
    UC  IronChest{6.0.103.753} [Iron Chest](ironchest-1.8-6.0.103.753-universal.jar) 
    UC  wuppy29_jellycubes{1.13.2} [Jelly Cubes](Jelly Cubes 1.8.0-1.13.2.jar) 
    UC  LagFix{2.0.2} [LagFix](LagFix-2.0.2-mc1.8-forge.jar) 
    UC  LunatriusCore{1.1.2.28} [LunatriusCore](LunatriusCore-1.8-1.1.2.28-universal.jar) 
    UC  LaserLevel{2.0.0.4} [Laser Level](LaserLevel-1.8-2.0.0.4-universal.jar) 
    UC  LavaBoat{2.1.0} [LavaBoat](LavaBoat-2.1.0.jar) 
    UC  LotsOfFood{1.8.1} [Lots of Food](Lots of Food-1.8.1.jar) 
    UC  lucky{6.0.0} [Lucky Block](LuckyBlock_1-8-3_v6-0-0.zip) 
    UC  MapWriter{2.2.5} [MapWriter](MapWriter-1.8-2.2.5.jar) 
    UC  mdecore{1.8-1.2.7} [MattDahEpic Core](mdecore-1.8-1.2.7.jar) 
    UC  maxanier_secondscreenmod{1.2.86} [Second Screen Mod](MinecraftSecondScreenMod-1.8-1.2.86.jar) 
    UC  mineralogy{2.5.1} [Mineralogy](mineralogy-2.5.1.jar) 
    UC  mymod{1.0} [Mo' Obsidian Stuff](Mo' Obsidian Stuff [1.8].jar) 
    UC  MobAmputation{5.0.0} [MobAmputation](MobAmputation-5.0.0.jar) 
    UC  deadlymobs{1.0} [More Deadly Mobs](More Deadly Mobs-1.0%281.8%29.jar) 
    UC  me{1.3.2.1} [More Enchantments](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  AencEx{0.0.1} [AencEx](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  Morpheus{1.8-2.0.41} [Morpheus](Morpheus-1.8-2.0.41.jar) 
    UC  samsmountedpearl{1.8-1.0.0} [Mounted Pearl](MountedPearl-1.8-1.0.0.jar) 
    UC  cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8-build1%281.8%29.jar) 
    UC  MultiPageChest{1.3.5} [Multi Page Chest](MultiPageChest-1.3.5-MC1.8.jar) 
    UC  neotech{2.0.5} [NeoTech](NeoTech-1.8-2.0.5.jar) 
    UC  wuppy29_nethereye{1.4.2} [Nether Eye](Nether Eye 1.8.0-1.4.2.jar) 
    UC  NoFov{1.0} [No Fov](NoFov-MC1.8-1.0.jar) 
    UC  recipehandler{1.8} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.3%281.8%29.jar) 
    UC  NoNausea{1.0} [No Nausea](NoNausea-MC1.8-1.0.jar) 
    UC  parachutemod{3.1.1} [Parachute Mod](parachutemod-1.8.0-3.1.2-96.jar) 
    UC  PeacefulSurface{1.8.x-v3} [PeacefulSurface](PeacefulSurface-1.8.x-v3.jar) 
    UC  PigManure{1.0.1} [Pig Manure](pig-manure-1.0.1.jar) 
    UC  plantmegapack{5.04} [Plant Mega Pack](plantmegapack-5.04-1.8-1334.jar) 
    UC  progressiveautomation{1.6.15} [Progressive Automation](ProgressiveAutomation-1.8-1.6.15.jar) 
    UC  ProjectE{1.8-PE1.0.1B} [ProjectE](ProjectE-1.8-PE1.0.1B.jar) 
    UC  ragdollCorpses{0.12} [Ragdoll Corpses](ragdollCorpses-0.12 for 1.8.jar) 
    UC  RandomThings{3.5.5} [Random Things](RandomThings-MC1.8-3.5.5.jar) 
    UC  realblocks{${version}} [Real Blocks](Real Blocks-v0.1.2.jar) 
    UC  redstonepaste{1.7.1} [Redstone Paste](redstonepaste-mc1.8-1.7.1.jar) 
    UC  Roguelike{1.3.6} [Roguelike Dungeons](RoguelikeDungeons-1.8-1.3.6.jar) 
    UC  searchcommands{1.8-1.0.0} [Search Commands](SearchCommands-1.8-1.0.0.jar) 
    UC  shadowstep{1.0} [Shadowstep](Shadowstep-1.0.jar) 
    UC  SimpleDimensions{1.0} [Simple Dimensions](SimpleDimensions-1.0.jar) 
    UC  wuppy29_slimedungeon{1.6.5} [Slime Dungeons](Slime Dungeon 1.8.0-1.6.5.jar) 
    UC  SlimevoidLib{3.0.0.4-beta-1.8} [Slimevoid Library](SlimevoidLibrary-3.0.0.4-beta-1.8.jar) 
    UC  wuppy29_snowgolem{1.6.2} [Clean Snow Golems](Snow Golem 1.8.0-1.6.2.jar) 
    UC  StorageDrawers{1.8-2.1.6} [Storage Drawers](StorageDrawers-1.8-2.1.6.jar) 
    UC  Talismans 2{2.1.2} [Talismans 2](Talismans2-1.8-2.1.2.jar) 
    UC  tau{1.8-1.1a} [Taunts!](Taunts!-1.8-1.1a.jar) 
    UC  telepacks{1.8-1.0} [TelePacks](telepacks-1.8-1.0.jar) 
    UC  reinforcedmod{Updated for 1.8} [Reinforced Mod](The Reinforced Mod 1.8%28v1.4.0%29.jar) 
    UC  arrowtrails{1.3_for_1.8} [Tmtravlr's Arrow Trails](TmtravlrsArrowTrails-1.3_for_1.8.jar) 
    UC  TrailMix{5.0.0} [TrailMix](TrailMix-5.0.0.jar) 
    UC  Waila{1.6.0_B1} [Waila](Waila-1.6.0_B1_1.8.1.jar) 
    UC  wailafeatures{0.0.1} [WAILA-features](WAILA-features-1.8-0.0.1.jar) 
    UC  WaitingMod{1.0.0} [WaitingMod](Wait Mod.zip) 
    UC  wallpaper{0.4} [Wallpaper](wallpaper-0.4-1.8.jar) 
    UC  wildcaves3{1.8} [Wild Caves 3](WildCaves3-0.4.3.7%281.8%29.jar) 
    UC  YALSM{2.1.5} [Yet Another Leather Smelting Mod](yalsm-2.1.5.jar) 
    UC  YUNoMakeGoodMap{1.8-5.0.0.13} [YUNoMakeGoodMap](YUNoMakeGoodMap-1.8-5.0.0.13-universal.jar) 
    UC  ZombieSunscreen{2.0} [Zombie Sunscreen](ZombieSunscreen.jar) 
    UC  denseores{1.0} [denseores](denseores-2.%28-1%29.0 %28alpha 1.8%29.jar) 
    UD  ZombieSunscreenCore{2.0} [ZombieSunscreenCore](minecraft.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
AllTheItems (AllTheItems-mc1.8-1.1.jar)
  net.fybertech.alltheitems.AllTheItems
FairyLightsLoadingPlugin (fairylights-1.2-1.8.jar)
  com.pau101.fairylights.core.FairyLightsClassTransformer
Init (RepairUnlimited1.8.jar)
  repairunlimit.Transformer
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
WallpaperLoadingPlugin (wallpaper-0.4-1.8.jar)
  com.pau101.wallpaper.core.WallpaperClassTransformer
BowInfinityFix (BowInfinityFix-1.8-rv1.jar)
  com.github.parker8283.bif.Transformer
LoadingPlugin (HardcoreDarkness-MC1.8-1.5.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)

LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
Transformer (EasyZoom[1.8][Forge].jar)
  easyzoom.Transformer
LoadingPlugin (VersionChecker-1.2.2.jar)

LoadingPlugin (Bloodmoon-1.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (FastLeaveDecay-1.0.jar)
  lumien.fastleavedecay.asm.ClassTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1373-universal.jar)

Core (NoSlimeInFlatland_v1.0.0[1.8].jar)
  nsf.Transformer
EWFMLPlugin ([1.8]ExtendedWorkbench v1.3 beta.jar)
  naruto1310.extendedWorkbench.EWTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
nceCore (NoCreeperExplosions_v1.0.1[1.8].jar)
  nce.nceLoader
Plugin (VillagerInv_v1.0.2[1.8][FML].jar)
  villagerinv.Plugin
ZSFMLLoadingPlugin (ZombieSunscreenCore.jar)
  com.lasa.zombiesunscreen.core.ZSClassTransformer
HxCLoader (HxCCore-1.8-1.5.1-universal.jar)
  HxCKDMS.HxCCore.Asm.HxCTransformer
Java8CheckerCoremod (Java8Checker  MC-1.8+  v1.1.jar)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (RandomThings-MC1.8-3.5.5.jar)
  lumien.randomthings.asm.ClassTransformer
MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
```

**Comment by RhysHolloway** [comment]
i think i had bookshelf 1.7 in there too...

**Comment by RhysHolloway** [comment]
not crashing anymore.
